name: run eslint

on:
  pull_request:

jobs:
  run_eslint:
    name: eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: yarn install
      - name: eslint
        run: yarn run eslint
